<?php
namespace VimServiceStub;

class ArrayOfDistributedVirtualSwitchManagerCompatibilityResult{
var $DistributedVirtualSwitchManagerCompatibilityResult;//DistributedVirtualSwitchManagerCompatibilityResult
}