<?php
namespace VimServiceStub;

class ArrayOfClusterDasFailoverLevelAdvancedRuntimeInfoHostSlots{
var $ClusterDasFailoverLevelAdvancedRuntimeInfoHostSlots;//ClusterDasFailoverLevelAdvancedRuntimeInfoHostSlots
}