<?php
namespace VimServiceStub;

class ArrayOfDistributedVirtualSwitchManagerHostDvsFilterSpec{
var $DistributedVirtualSwitchManagerHostDvsFilterSpec;//DistributedVirtualSwitchManagerHostDvsFilterSpec
}