<?php
namespace VimServiceStub;

class ArrayOfHostLowLevelProvisioningManagerSnapshotLayoutSpec{
var $HostLowLevelProvisioningManagerSnapshotLayoutSpec;//HostLowLevelProvisioningManagerSnapshotLayoutSpec
}