<?php
namespace VimServiceStub;

class ArrayOfClusterFailoverHostAdmissionControlInfoHostStatus{
var $ClusterFailoverHostAdmissionControlInfoHostStatus;//ClusterFailoverHostAdmissionControlInfoHostStatus
}