<?php
namespace VimServiceStub;

class HostCapability{
var $recursiveResourcePoolsSupported;//boolean
var $cpuMemoryResourceConfigurationSupported;//boolean
var $rebootSupported;//boolean
var $shutdownSupported;//boolean
var $vmotionSupported;//boolean
var $standbySupported;//boolean
var $ipmiSupported;//boolean
var $maxSupportedVMs;//int
var $maxRunningVMs;//int
var $maxSupportedVcpus;//int
var $datastorePrincipalSupported;//boolean
var $sanSupported;//boolean
var $nfsSupported;//boolean
var $iscsiSupported;//boolean
var $vlanTaggingSupported;//boolean
var $nicTeamingSupported;//boolean
var $highGuestMemSupported;//boolean
var $maintenanceModeSupported;//boolean
var $suspendedRelocateSupported;//boolean
var $restrictedSnapshotRelocateSupported;//boolean
var $perVmSwapFiles;//boolean
var $localSwapDatastoreSupported;//boolean
var $unsharedSwapVMotionSupported;//boolean
var $backgroundSnapshotsSupported;//boolean
var $preAssignedPCIUnitNumbersSupported;//boolean
var $screenshotSupported;//boolean
var $scaledScreenshotSupported;//boolean
var $storageVMotionSupported;//boolean
var $vmotionWithStorageVMotionSupported;//boolean
var $recordReplaySupported;//boolean
var $ftSupported;//boolean
var $replayUnsupportedReason;//string
var $replayCompatibilityIssues;//string
var $ftCompatibilityIssues;//string
var $loginBySSLThumbprintSupported;//boolean
var $cloneFromSnapshotSupported;//boolean
var $deltaDiskBackingsSupported;//boolean
var $perVMNetworkTrafficShapingSupported;//boolean
var $tpmSupported;//boolean
var $supportedCpuFeature;//HostCpuIdInfo
var $virtualExecUsageSupported;//boolean
var $storageIORMSupported;//boolean
var $vmDirectPathGen2Supported;//boolean
var $vmDirectPathGen2UnsupportedReason;//string
var $vmDirectPathGen2UnsupportedReasonExtended;//string
var $supportedVmfsMajorVersion;//int
var $vStorageCapable;//boolean
var $snapshotRelayoutSupported;//boolean
var $firewallIpRulesSupported;//boolean
var $servicePackageInfoSupported;//boolean
var $maxHostRunningVms;//int
var $maxHostSupportedVcpus;//int
var $vmfsDatastoreMountCapable;//boolean
}