<?php
namespace VimServiceStub;

class VirtualMachineConfigInfo{
var $changeVersion;//string
var $modified;//dateTime
var $name;//string
var $guestFullName;//string
var $version;//string
var $uuid;//string
var $instanceUuid;//string
var $npivNodeWorldWideName;//long
var $npivPortWorldWideName;//long
var $npivWorldWideNameType;//string
var $npivDesiredNodeWwns;//short
var $npivDesiredPortWwns;//short
var $npivTemporaryDisabled;//boolean
var $npivOnNonRdmDisks;//boolean
var $locationId;//string
var $template;//boolean
var $guestId;//string
var $alternateGuestName;//string
var $annotation;//string
var $files;//VirtualMachineFileInfo
var $tools;//ToolsConfigInfo
var $flags;//VirtualMachineFlagInfo
var $consolePreferences;//VirtualMachineConsolePreferences
var $defaultPowerOps;//VirtualMachineDefaultPowerOpInfo
var $hardware;//VirtualHardware
var $cpuAllocation;//ResourceAllocationInfo
var $memoryAllocation;//ResourceAllocationInfo
var $memoryHotAddEnabled;//boolean
var $cpuHotAddEnabled;//boolean
var $cpuHotRemoveEnabled;//boolean
var $hotPlugMemoryLimit;//long
var $hotPlugMemoryIncrementSize;//long
var $cpuAffinity;//VirtualMachineAffinityInfo
var $memoryAffinity;//VirtualMachineAffinityInfo
var $networkShaper;//VirtualMachineNetworkShaperInfo
var $extraConfig;//OptionValue
var $cpuFeatureMask;//HostCpuIdInfo
var $datastoreUrl;//VirtualMachineConfigInfoDatastoreUrlPair
var $swapPlacement;//string
var $bootOptions;//VirtualMachineBootOptions
var $ftInfo;//FaultToleranceConfigInfo
var $vAppConfig;//VmConfigInfo
var $vAssertsEnabled;//boolean
var $changeTrackingEnabled;//boolean
var $firmware;//string
var $maxMksConnections;//int
var $guestAutoLockEnabled;//boolean
var $managedBy;//ManagedByInfo
var $memoryReservationLockedToMax;//boolean
var $initialOverhead;//VirtualMachineConfigInfoOverheadInfo
}