<?php
namespace VimServiceStub;

class VirtualMachineConfigSpec{
var $changeVersion;//string
var $name;//string
var $version;//string
var $uuid;//string
var $instanceUuid;//string
var $npivNodeWorldWideName;//long
var $npivPortWorldWideName;//long
var $npivWorldWideNameType;//string
var $npivDesiredNodeWwns;//short
var $npivDesiredPortWwns;//short
var $npivTemporaryDisabled;//boolean
var $npivOnNonRdmDisks;//boolean
var $npivWorldWideNameOp;//string
var $locationId;//string
var $guestId;//string
var $alternateGuestName;//string
var $annotation;//string
var $files;//VirtualMachineFileInfo
var $tools;//ToolsConfigInfo
var $flags;//VirtualMachineFlagInfo
var $consolePreferences;//VirtualMachineConsolePreferences
var $powerOpInfo;//VirtualMachineDefaultPowerOpInfo
var $numCPUs;//int
var $numCoresPerSocket;//int
var $memoryMB;//long
var $memoryHotAddEnabled;//boolean
var $cpuHotAddEnabled;//boolean
var $cpuHotRemoveEnabled;//boolean
var $virtualICH7MPresent;//boolean
var $virtualSMCPresent;//boolean
var $deviceChange;//VirtualDeviceConfigSpec
var $cpuAllocation;//ResourceAllocationInfo
var $memoryAllocation;//ResourceAllocationInfo
var $cpuAffinity;//VirtualMachineAffinityInfo
var $memoryAffinity;//VirtualMachineAffinityInfo
var $networkShaper;//VirtualMachineNetworkShaperInfo
var $cpuFeatureMask;//VirtualMachineCpuIdInfoSpec
var $extraConfig;//OptionValue
var $swapPlacement;//string
var $bootOptions;//VirtualMachineBootOptions
var $vAppConfig;//VmConfigSpec
var $ftInfo;//FaultToleranceConfigInfo
var $vAppConfigRemoved;//boolean
var $vAssertsEnabled;//boolean
var $changeTrackingEnabled;//boolean
var $firmware;//string
var $maxMksConnections;//int
var $guestAutoLockEnabled;//boolean
var $managedBy;//ManagedByInfo
var $memoryReservationLockedToMax;//boolean
}